#!/bin/python3
train_mass = 200
train_acceleration = 5
bomb_energy = 20 
bomb_mass = 40
train_distance = 50
train_work = 10
mass = 5
acceleration = 40 

def f_to_c(f_temp):
	return (f_temp -32) * 5/9

def c_to_f(c_temp):
	return (c_temp *9/5) + 32

f100_in_celsius = f_to_c(100)

c0_in_fahrenheit =c_to_f(0)

def get_force(mass,acceleration):
	return mass * acceleration

train_force = get_force(train_mass,train_acceleration)
print ("The GE train supplies " + str(train_force) + " Newtons of force ")


def get_energy(mass,c=3*10**8):
	return mass * c**2

bomb_energy = get_energy(bomb_mass)
print ("A 1 kg bomb supplies " + str(bomb_energy) + " Joules.")

def get_work(mass,acceleration,distance):
	force = get_force(mass,acceleration)
	return force * distance 


train_work = get_work(train_mass,train_acceleration,train_distance)
print ("The GE train does " + str(train_work) + " Joules of work over " +  str(train_distance) + " metters.") 
